### ISSUE TITLE
Need more info: where can I find the correct value for the field "Host Server"

### ISSUE THREAD

**Issue by mango009** [WowzaMediaSystems/wsc-webrtc-example#3]
I'm reading the instruction in [here](https://www.wowza.com/docs/connect-a-webrtc-stream-to-wowza-streaming-cloud) . In #4 it says to use the "Source Connection" in the "Overview" tab to configure the stream setting. Exactly which page it is referring? Where is the "Overview" tab?

Can the "application name" and "stream name" be arbitrary?

Also in the READ.me of the [page](https://github.com/WowzaMediaSystems/wsc-webrtc-example), it says that ' In order for the example to work properly, the transcoder's stream extension must be set to .json'. What does it mean?

**Comment by akeller** [comment]
Overview tab refers to your Live Stream you've created on [Wowza Streaming Cloud](cloud.wowza.com). Login, click Live Streams in the top menu and find your live stream. You'll see you the page loads in the Overview tab and roughly in the middle is your Source Connection Information.

Application name and stream name can be arbitrary, in so much as they need to match on your WebRTC client/browser page and the live stream being referenced in Wowza Streaming Cloud. 

When creating your live stream, make sure your Camera/Encoder is set to Web Browser(WebRTC). 

If you are still stuck, let me know and I can include screenshots of each step along the way.

**Comment by mango009** [comment]
So this example assume there's already a stream created by the console. I should have read the instructions more clearly. 

Is there an example showing me how to create a stream programmatically? Is it simply a REST call with proper parameters?

Another question as I mentioned earlier: you README.md says that ' In order for the example to work properly, the transcoder's stream extension must be set to .json'. Can you be more specific why this is the case?

**Comment by akeller** [comment]
You are correct in your thinking that it is a REST call with proper parameters. Read more about it here - https://www.wowza.com/docs/connect-a-webrtc-stream-to-wowza-streaming-cloud-using-the-wowza-streaming-cloud-rest-api

The SDP data is passed via json using a websocket between the client (browser) and Wowza Streaming Cloud. You can see this in the [publish code](https://github.com/WowzaMediaSystems/wsc-webrtc-example/blob/master/html/publish/webrtc.js). I believe in our Wowza Streaming Cloud implementation we now handle all of this for you when you specify the encoder as `other_webrtc`.

**Comment by mango009** [comment]
Thank you.
