### ISSUE TITLE
Failed to do perf connection in webrtc.js

### ISSUE THREAD

**Issue by mango009** [WowzaMediaSystems/wsc-webrtc-example#4]
I'm running in Safari 13.1.1. and when I click the 'publish' button the webrtc.js failed with the following message in the console. Please see the attached screen grab.

![Screen Shot 2020-07-01 at 3 49 48 PM](https://user-images.githubusercontent.com/2007039/86298401-851c0400-bbb2-11ea-97d1-956914b2be0a.png)

**Comment by mango009** [comment]
It seems like a javascript compatibility problem in webrtc.js. It runs fine in chrome.

Do you guys have a webrtc client SDK  that works across most browsers?

I also notice a 25 seconds delay of the video feed when I open a browser on a separate PC pointing to the hosted page in Wowza cloud. This to me is a bigger problem. I'm sure this cannot be the case but what causes the delay?

**Comment by akeller** [comment]
We've noticed Safari is a bit behind Chrome and Firefox with WebRTC and other Media API compatibility. We are looking at consolidating our WebRTC examples to a [single repo](https://github.com/WowzaMediaSystems/webrtc-examples/) to focus on better cross-browser cross-platform functionality.

We do not offer a client SDK, just examples at this time.

There will be a delay as you are going WebRTC > Wowza Streaming Cloud (transcoding) > HLS, but not typically 25 seconds. Did you create a reduced latency HLS stream? I would recommend looking at our transcoder documentation for more parameters to tweak this to something more acceptable - https://api.docs.cloud.wowza.com/current/tag/transcoders

I would also recommend opening a support ticket if you have more questions about WebRTC workflows.

**Comment by mango009** [comment]
Thank you. I suspect the latency could be due to my uplink speed this afternoon. I think it would be helpful if you guys can provide some sort of dash board to measure the throughput between the publisher and Wowza cloud, and the throughput between the Wowza cloud to the subscriber.
